export const BAIRROS_ETIC = [
  'Aclimação',
  'Água Branca',
  'Água Rasa',
  'Alto da Lapa',
  'Alto da Mooca',
  'Alto de Pinheiros',
  'Anália Franco',
  'Barra Funda',
  'Bela Vista',
  'Belenzinho',
  'Bom Retiro',
  'Brás',
  'Brooklin',
  'Butantã',
  'Cambuci',
  'Campo Belo',
  'Carrão',
  'Centro',
  'Cerqueira César',
  'Chácara Klabin',
  'Consolação',
  'Higienópolis',
  'Ipiranga',
  'Itaim Bibi',
  'Jabaquara',
  'Jardim Paulista',
  'Jardins',
  'Lapa',
  'Liberdade',
  'Moema',
  'Mooca',
  'Morumbi',
  'Pacaembu',
  'Paraíso',
  'Perdizes',
  'Pinheiros',
  'Pompeia',
  'República',
  'Santa Cecília',
  'Santa Cruz',
  'Saúde',
  'Sumaré',
  'Tatuapé',
  'Vila Mariana',
  'Vila Prudente',
].sort()
