export const regionsData = [
  {
    anchor: 'Mooca',
    satellites: [
      'Alto da Mooca',
      'Parque da Mooca',
      'Vila Oratório',
      'Belenzinho',
      'Brás',
      'Água Rasa',
      'Quarta Parada',
      'Vila Bertioga',
      'Vila Cláudia',
      'Vila Invernada',
      'Vila Lúcia',
      'Jardim Itália',
    ],
  },
  {
    anchor: 'Tatuapé',
    satellites: [
      'Vila Zilda',
      'Maranhão',
      'Vila Azevedo',
      'Vila Gomes Cardim',
      'Chácara Santo Antônio',
      'Vila Lusitana',
      'Vila São Jorge',
      'Vila Moreira',
      'Vila Silvio',
      'Parque São Jorge',
      'Vila Santo Estêvão',
      'Tatuapé Centro',
    ],
  },
  {
    anchor: 'Carrão',
    satellites: [
      'Vila Carrão',
      'Vila Nova Manchester',
      'Vila Santa Isabel',
      'Chácara Califórnia',
      'Chácara Santo Antônio (ZL)',
      'Vila Antonieta',
      'Vila Formosa',
      'Vila Dalila',
      'Vila Matilde',
      'Vila Guilhermina',
      'Vila Talarico',
      'Jardim Têxtil',
    ],
  },
  {
    anchor: 'Vila Prudente',
    satellites: [
      'Vila Prudente Centro',
      'Parque São Lucas',
      'Vila Alpina',
      'Vila Zelina',
      'Jardim Avelino',
      'Vila Bela',
      'Vila Califórnia',
      'Parque da Vila Prudente',
      'Vila Alois',
      'Jardim Ibitirama',
      'Vila Lucia',
      'Jardim Independência',
    ],
  },
  {
    anchor: 'Ipiranga',
    satellites: [
      'Ipiranga Centro',
      'Alto do Ipiranga',
      'Vila Monumento',
      'Vila São José',
      'Vila Carioca',
      'Vila Independência',
      'Vila Eulália',
      'Vila Dom Pedro I',
      'Sacomã',
      'Heliópolis',
      'Moinho Velho',
      'São João Clímaco',
    ],
  },
  {
    anchor: 'Vila Ema',
    satellites: [
      'Vila Ema Centro',
      'Vila Tolstoi',
      'Vila Industrial',
      'Vila Guarani',
      'Vila Graciosa',
      'Vila Diva',
      'Vila Cunha Bueno',
      'Vila Mendes',
      'Vila Nova',
      'Jardim Guairaca',
      'Parque São Lourenço',
      'Vila Central',
    ],
  },
]
